[project]
name = "mytelegrambot"
version = "0.1.0"
description = "My Telegram Bot"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiohttp==3.9.3",
    "apscheduler>=3.11.3",
    "async-lru>=2.1.0",
    "beanie>=1.29.0",
    "kurigram>=2.2.25",
    "loguru>=0.7.3",
    "pydantic-settings-yaml>=0.2.0",
    "reloadium>=1.5.1",
    "tgcrypto==1.2.3",
    "uvloop>=0.21.0 ; sys_platform != 'win32'",
]

[dependency-groups]
dev = [
    "mkinit>=1.2.0",
    "reloadium>=1.5.1",
]
